### ISSUE TITLE
Highlight `var` keyword

### ISSUE THREAD

**Issue by mtman** [atom/language-java#162]
Java 10 `var` keyword is not highlighted, which makes declarations visually ambiguous with calls. That makes code significantly harder to navigate.

**Comment by sadikovi** [comment]
Can you post screenshots/snippets of what it looks like in Java 10?

**Comment by mtman** [comment]
![image](https://user-images.githubusercontent.com/15874394/45595572-684b1800-b9ae-11e8-9f95-60b77a8f4081.png)

In case of second declaration, `var` is not recognized as `storage.type` and `launchSpecification` as `variable.other`.

**Comment by mtman** [comment]
Another scenario is `for (var c : new C()) { }`. The following regex covers all declarations: `\\b(var)\\b\\s+[A-Za-z_$][\\w$]*\\b\\s*[=:]`


> There are some valid arguments for and against having var.

`var` is intrinsically expected to be highlighted alongside `void` and real types. Both Eclipse and Intellij work that way. Here's a more on point discussion: https://bugs.eclipse.org/bugs/show_bug.cgi?id=532313

One improvement would be highlighting `void`,`var` and the primitive types as keywords, while `class C` and `new X()`, except the primitive types as complex types. Currently `new X()` is incorrectly highlighted as a method for unlisted types, but that should be a new issue.

**Comment by sadikovi** [comment]
Thanks @mtman! That is very useful, I forgot about for loops. Let me know if you would like to open a PR to add support for `var`, otherwise I will try fixing it this weekend:). 

@50Wliu how would you go about adding `var` support? Would love to hear your opinion on the issue.

@mtman I did not get part with `new X()`. I am pretty sure it is highlighted correctly in the context of `X x = new X();`.  Would you mind to clarify that statement?

**Comment by sadikovi** [comment]
Hi @mtman, sorry to hear that. I will try pushing forward the fix with your
suggestions, thanks a lot for raising the issue. I will also have a look at
another problem that you have pointed out, though, frankly speaking, I am
just used to that highlighting:).

What is the name of the plugin or a project - I can also have a look when I
have time and fix a couple of bugs:).

I hope you will return to Atom in the future, since it is actually a good
editor, and a lot of effort is being made to make even better!

**Comment by mtman** [comment]
@sadikovi The plugin is for VS Code, but it apparently uses this package, see https://github.com/redhat-developer/vscode-java/issues/604 It has issues like random delays for auto completion to show up, or sometimes errors that were e.g. commented out prevent the build to succeed. 

Thanks for your effort, it's always useful to have multiple editors that are competitive.
