### ISSUE TITLE
Highlighting is wrong 

### ISSUE THREAD

**Issue by V0idk** [atom/language-java#169]
![image](https://user-images.githubusercontent.com/17514799/47998590-dd2f0880-e13a-11e8-8061-cc0535885da6.png)

**Comment by sadikovi** [comment]
Please use issue template that is provided when you create one, thanks.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sadikovi** [comment]
I don't think we should have closed the issue. It may be relatively easy to fix, actually. @V0idk, would you mind adding a bit of information to the ticket and fill out the template? I am thinking on fixing it together with handling `=` in the properties' declarations. Thanks.
