### ISSUE TITLE
custom Trigger for System.out.format()/System.out.printf()

### ISSUE THREAD

**Issue by jagadeeshvarma** [atom/language-java#62]
For now **`pl`** Trigger works for `System.out.println(); `and  **`p`** works for `System.out.print();`
How can I add my own shortcut to print `System.out.format();` and `System.out.printf();`?

![print](https://cloud.githubusercontent.com/assets/4271270/17393075/e731a4da-5a3e-11e6-9ff8-4d19eeb7c09f.JPG)

**Comment by 50Wliu** [comment]
If you want to add those to the language-java package, you can do so by editing [this file](https://github.com/atom/language-java/blob/master/snippets/language-java.cson).  Otherwise, if it's just for your own use, you can add your own snippets through the _Atom > Snippets..._ menu option on Mac, _File > Snippets..._ on Windows, or _Edit > Snippets..._ on Linux.

**Comment by jagadeeshvarma** [comment]
Thanks a lot @50Wliu 
I've added the entry in Sinppets file which is working fine.
Also added the same in [this file](https://github.com/atom/language-java/blob/master/snippets/language-java.cson).
