### ISSUE TITLE
Java language syntax hilighter treats semicolon wrong inside both single and double quotes

### ISSUE THREAD

**Issue by igorvolnyi** [atom/language-java#87]
atom 1.16 on ArchLinux. See attached source file and screenshots
[bug.zip](https://github.com/atom/language-java/files/923174/bug.zip)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
