### ISSUE TITLE
Commented method after constructor is not highlighted properly

### ISSUE THREAD

**Issue by lobisquit** [atom/language-java#92]
### Description

I have noticed that commented a method after a constructor leaves it the usual color, i.e. it is not greyed out. I have tried with a fresh install on Arch Linux 64bit and the bug is still there.

**Expected behavior:** 
Proper highlight is triggered when the object is not constructed right before, as you can see here.
![spectacle ea7400](https://cloud.githubusercontent.com/assets/15218169/26024472/1ec8bf20-37d2-11e7-9203-2e2ff9c50fcb.png)

**Actual behavior:** 
When doing the two steps in one shot, the problem arises: as you can see `.setAppName(...)` is not grayed.
![spectacle uv7400](https://cloud.githubusercontent.com/assets/15218169/26024483/51fe4130-37d2-11e7-8540-2e0e1332a4f5.png)

### Versions

My system is Arch Linux 64bit (up-to-date).

Atom version:
```
Atom    : 1.16.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

Apm version:
```
apm  1.18.1
npm  4.5.0
node 7.10.0 x64
python 2.7.13
git 2.13.0
```

**Comment by 50Wliu** [comment]
> Electron: 1.4.16

Thanks for reaching out!

We've determined that you are using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).  If you can still reproduce the problem on an official distribution of Atom, please feel free to create a new issue.
